In [ ]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, chi2

In [143]:
df = pd.read_csv("tested.csv")

In [144]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [145]:
df = df.drop(columns=["PassengerId","Name","Ticket","Cabin"])

In [146]:
df.head(2)

   Survived  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0         0       3    male  34.5      0      0  7.8292        Q
1         1       3  female  47.0      1      0  7.0000        S

In [147]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [148]:
df.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

In [149]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["Survived"]),df["Survived"],test_size= 0.2,random_state=42)

In [150]:
X_train

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
336       2  male  32.0      0      0  13.0000        S
31        2  male  24.0      2      0  31.5000        S
84        2  male   NaN      0      0  10.7083        Q
287       1  male  24.0      1      0  82.2667        S
317       2  male  19.0      0      0  10.5000        S
..      ...   ...   ...    ...    ...      ...      ...
71        3  male  21.0      0      0   7.8958        S
106       3  male  21.0      0      0   7.8208        Q
270       1  male  46.0      0      0  75.2417        C
348       2  male  24.0      0      0  13.5000        S
102       3  male   NaN      0      0   7.7500        Q

[334 rows x 7 columns]

#Building the Pipeline

In [151]:
trf1 = ColumnTransformer([
    ("impute_age",SimpleImputer(),[2]),
    ("impute_fare",SimpleImputer(),[5])
],remainder='passthrough')

In [152]:
trf2 = ColumnTransformer([
    ('sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder ='passthrough')

In [153]:
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
    
])

In [154]:
trf4 = SelectKBest(score_func=chi2, k=5)

In [155]:
trf5 = DecisionTreeClassifier()

#Crete PipeLine

In [156]:
pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [157]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_fare',
                                                  SimpleImputer(), [5])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x0000019A61564F40>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [158]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_fare', SimpleImputer(), [5])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=5, score_func=<function chi2 at 0x0000019A61564F40>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [159]:
y_pred = pipe.predict(X_test)

In [160]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
prediction = accuracy_score(y_test,y_pred)

In [162]:
print(prediction)

0.5952380952380952

#Expoting the pipline

In [169]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))